# spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cybz  # 数据库地址
    username: root   # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 驱动类名
    hikari:
      connection-timeout: 20000  # 连接超时时间
      maximum-pool-size: 10  # 连接池最大连接数
      minimum-idle: 5  # 连接池最小连接数
      idle-timeout: 30000  # 连接池空闲时间
      max-lifetime: 60000  # 连接池最大连接时间
      auto-commit: true  # 自动提交
      allow-pool-suspension: true  # 允许池暂停
  devtools:
    restart:
      enabled: true  # 默认启用自动重启
      exclude: static/**,public/**  # 排除无需重启的静态资源路径
      trigger-file: .reloadtrigger  # 项目级配置
  mvc:
    log-request-details: true  # 记录请求头、参数等详细信息
  codec:
    log-request-details: true  # WebFlux 应用启用
  thymeleaf:
    cache: false   # 显式禁用 Thymeleaf 缓存
  freemarker:
    cache: false  # 禁用 FreeMarker 缓存
  web:
    resources:
      static-locations: classpath:static/, file:public/  # 静态资源路径
      cache:
        period: 0  # 静态资源缓存时间
      chain:
        cache: false  # 禁用静态资源链

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtpdm.aliyun.com  # 邮件服务器
    port: 465   # 邮件服务器端口
    username: cybzacg@ali01.cybzacg.xyz  # 邮件服务器用户名
    password: QWEasdzxc123  # 邮件服务器密码
    default-encoding: UTF-8  # 邮件编码
    properties:
      mail:
        smtp:
          ssl:
            enable: true  # 开启SSL
  elasticsearch:
    uris: https://localhost:9200  # es地址
    username: elastic  # es用户名
    password: AqymD4+rdK=34c*-MjHO  # es密码
    connection-timeout: 5000  # 连接超时时间
    socket-timeout: 30000  # 套接字超时时间
  data:
    mongodb:
      host: localhost  # mongodb地址
      port: 27017  # mongodb端口
      database: cybz  # 数据库名
    redis:
      host: localhost  # redis地址
      port: 6379  # redis端口
      timeout: 5000  # 连接超时时间
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数
          max-idle: 4  # 连接池最大空闲连接数
          min-idle: 1  # 连接池最小空闲连接数
          time-between-eviction-runs: 60s  # 连接池空闲连接扫描间隔
  rabbitmq:
    publisher-returns: true  # 开启消息发送确认
    publisher-confirm-type: correlated  # 发送确认模式
    host: localhost          # 如果是远程服务器，替换为实际 IP
    port: 5672               # AMQP 协议端口
    username: admin          # 你设置的默认用户
    password: 123456         # 你设置的密码
    connection-timeout: 5000  # 连接超时时间
    virtual-host: /   # 虚拟主机
    listener:
      type: simple  # 监听器类型
      simple:
        acknowledge-mode: auto #确认模式
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        retry: #重试策略相关配置
          enabled: true  # 开启消费者(程序出现异常)重试机制，默认开启并一直重试
          max-attempts: 5 # 最大重试次数
          initial-interval: 3000 # 重试间隔时间(毫秒)

logging:
  level:
    root: info  # 日志级别
    org:
      springframework:
        web: debug  # 显示SpringMVC请求日志
        data:
          mongodb: debug
    com:
      example:
        douyin:
          mapper: debug  # 显示Mapper日志
    controller: debug

  file:
    name: logs/app.log  # 当前活跃日志文件
  logback:
    rollingpolicy:
      max-file-size: 5MB  # 日志文件最大大小
      max-history: 7  # 日志文件保留天数
      total-size-cap: 300MB  # 日志文件总大小
      filename-pattern: logs/app-%d{yyyy-MM-dd}-%i.log  # 包含日期和索引
  group:
    controller: com.example.cybz_back.controller


# 管理端点和健康检查
management:
  endpoint:
    health:
      show-details: always  # 显示健康详细信息
  health:
    db:
      enabled: true  # postgresql健康检查

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml  # 指定XML映射文件位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出SQL到控制台
    map-underscore-to-camel-case: true  # 字段自动驼峰映射
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto   # 主键策略（根据数据库自增）
      logic-delete-field: del_flag  # 逻辑删除字段
      logic-delete-value: 1   # 删除标记值
      logic-not-delete-value: 0  # 未删除标记

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # swagger-ui路径
    tags-sorter: alpha  # 标签排序
    operations-sorter: alpha  # 操作排序
  api-docs:
    path: /v3/api-docs  # openapi-docs路径

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true  # 开启增强
  setting:
    language: zh_cn  # 默认语言

# 定义缓存
cache:
  type: redis  # 缓存类型， 共有（redis， caffeine，不配置默认使用ehCache）

# 自定义属性

default:
  captcha:
    expiration: 300  # 验证码过期时间，单位秒
  frequency:
    number: 5  # 默认发送频率限制
    frequency-time: 600  # 默认每次发送时间间隔，单位秒
    banned: 86400  # 超过频率限制后，被禁止的时间，单位秒
  jwt:
    expiration: 604800
    secret: rI7kK0pK0hD8dK9oQ6kR0bK3dF1mJ7dT2yM3wT7yF9fT5mX1aX4aH0gB6rL1vZ4gI1jG3qC8
    issuer: douyin-app

  cache:
    redis:
      expireTime: 300
      userExpireTime: 300
      productExpireTime: 5
    caffe:
      expireTime: 300
      maxSize: 1000
    ehcache:
      expireTime: 600
      maxSize: 1000
  file:
    image:
      avatar: /static/images/avatar
      background: /static/images/background
      test: /static/images/test
      processing:
        quality: 0.7

